import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";
import { RegionProvider } from "@/providers/region";
import { ThemeProvider } from "next-themes";
import Navbar from "@/modules/Layout/Navbar";
import Footer from "@/modules/Layout/Footer";

const SpaceGroteskFont = localFont({
  src: "../fonts/SpaceGrotesk.ttf"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${SpaceGroteskFont.className} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <RegionProvider>
            <Navbar />
            <main className="px-2 sm:px-4 md:px-6 mx-auto max-w-7xl min-h-screen">
              {children}
            </main>
            <Footer />
          </RegionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
