import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";
import { RegionProvider } from "@/providers/region";
import { ThemeProvider } from "next-themes";
import Navbar from "@/modules/Layout/Navbar";
import Footer from "@/modules/Layout/Footer";
import { cookies } from "next/headers";
import { sdk } from "@/lib/sdk";
import { StoreProvider } from "@/providers/store-provider";
import { Toaster } from "@/components/ui/sonner";

const SpaceGroteskFont = localFont({
  src: "../fonts/SpaceGrotesk.ttf"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userCookies = await cookies();
  const cartId = userCookies.get("cartId")?.value.toString()
  const cartData = await sdk.store.cart.retrieve(cartId!)
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${SpaceGroteskFont.className} antialiased`}
      >
        <Toaster />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <RegionProvider>
            <StoreProvider preloadedState={{
              cart: {
                items: cartData?.cart?.items || [],
                loading: false,
                error: null,
              },
            }}>
              <Navbar />
              <main className="px-2 sm:px-4 md:px-6 mx-auto max-w-7xl min-h-screen">
                {children}
              </main>
            </StoreProvider>
            <Footer />
          </RegionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
